---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: traefik-ingress-controller-transformer
  labels:
    k8s-app: traefik-ingress-lb-transformer
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: traefik-ingress-lb-transformer
  template:
    metadata:
      labels:
        k8s-app: traefik-ingress-lb-transformer
        name: traefik-ingress-lb-transformer
    spec:
      serviceAccountName: traefik-ingress-controller-transformer
      terminationGracePeriodSeconds: 60
      volumes:
      - name: ssl
        secret:
          secretName: traefik-cert-transformer
      - name: config
        configMap:
          name: traefik-conf-transformer
      containers:
      - image: traefik:1.7
        name: traefik-ingress-lb-transformer
        imagePullPolicy: Always
        volumeMounts:
        - mountPath: "/ssl"
          name: "ssl"
        - mountPath: "/config"
          name: "config"
        args:
        - --web
        - --configfile=/config/traefik.toml
        - --logLevel=DEBUG
---
kind: Service
apiVersion: v1
metadata:
  name: traefik-ingress-service-transformer
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
    service.beta.kubernetes.io/azure-load-balancer-internal-subnet: "ingressnet"
spec:
  type: LoadBalancer
  selector:
    k8s-app: traefik-ingress-lb-transformer
  ports:
    - protocol: TCP
      port: 80
      name: http
    - protocol: TCP
      port: 443
      name: https
    - protocol: TCP
      port: 8080
      name: admin

